AWSTemplateFormatVersion: "2010-09-09"
Description: S3 bucket + CloudFront static website

#-------------------------------------------------------------------------------
#--[ PARAMETERS ]---------------------------------------------------------------
#-------------------------------------------------------------------------------

Parameters:
  AcmCertificateArn:
    Description: Certificate Arn for cloudfront
    Type: AWS::SSM::Parameter::Value<String>
  DomainName:
    Description: Register new domain name
    Type: AWS::SSM::Parameter::Value<String>
  HostedZoneName:
    Description: Route 53 hosted zone name
    Type: AWS::SSM::Parameter::Value<String>
  Record:
    Description: Record name for the website endpoint (without the domain name, for example www for www.happyculteur.co)
    Type: AWS::SSM::Parameter::Value<String>

Resources:
  S3WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
    DeletionPolicy: Retain

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3WebsiteBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                -
                  - "arn:aws:s3:::"
                  -
                    Ref: "S3WebsiteBucket"
                  - "/*"
            Principal: "*"

  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Ref DomainName
        Origins:
        - CustomOriginConfig:
            OriginProtocolPolicy: http-only
          DomainName: !Select [ "2" , !Split [ "/" , !GetAtt S3WebsiteBucket.WebsiteURL ] ]
          Id: S3BucketWebHosting
        Enabled: true
        HttpVersion: 'http2'
        DefaultRootObject: index.html
        Aliases:
        - !Ref DomainName
        DefaultCacheBehavior:
          AllowedMethods: ["HEAD", "GET"]
          Compress: false
          TargetOriginId: S3BucketWebHosting
          ForwardedValues:
            QueryString: 'true'
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.1_2016

  DNSRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt CloudfrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      Comment: Managed by CloudFormation
      HostedZoneName: !Ref HostedZoneName
      Name: !Join ['.', [ !Ref Record , !Ref HostedZoneName ]]
      Type: A

  DNSRecordSetIPv6:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt CloudfrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      Comment: Managed by CloudFormation
      HostedZoneName: !Ref HostedZoneName
      Name: !Join ['.', [ !Ref Record , !Ref HostedZoneName ]]
      Type: AAAA
